export enum IconKind {
  BOLD_MAN_WITH_BEARD = "bold_man_with_beard",
  MAN_WITH_BEARD_AND_GLASSES = "man_with_beard_and_glasses",
  MAN_WITH_GLASSES = "man_with_glasses",
  MAN_WITH_LONG_HAIR = "man_with_long_hair",
  MAN_WITH_SHORT_HAIR = "man_with_short_hair",
  MAN_WITH_SHORT_HAIR2 = "man_with_short_hair2",
  WOMAN_WITH_GLASSES_AND_LONG_HAIR = "woman_with_glasses_and_long_hair",
  WOMAN_WITH_HABIB = "woman_with_habib",
  WOMAN_WITH_LONG_CURLY_HAIR = "woman_with_long_curly_hair",
  WOMAN_WITH_LONG_HAIR_TO_ONE_SIDE = "woman_with_long_hair_to_one_side",
  WOMAN_WITH_LONG_HAIR = "woman_with_long_hair",
  WOMAN_WITH_SHORT_HAIR = "woman_with_short_hair",
  WOMAN_WITH_TIED_HAIR = "woman_with_tied_hair",
  EDIT = "edit",
  EMPTY = "empty",
  CLOSE = "close",
  CHECK = "check",
  BROKEN_IMAGE = "broken_image",
  EXPAND_MORE = "expand_more",
  TEXT_FIELDS = "text_fields",
  TEXT_ICON = "text_icon",
  IMAGE_ICON = "image_icon",
}
